#普通数据配置
name: zhangsan

#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing

#行内对象配置
#person1: {name: zhangsan,age: 18,addr: beijing }
server:
  port: 8088

#配置数组或者集合（普通字符串）
city:
  - beijing
  - nanjing
  - chongqin
  - shanghai
#行内配置
#city1: [beijing,tianjin,chongqing,shanghai]

#配置数据，集合（对象数据）
student:
  - name: tom
    age: 18
    addr: beijing
  - name: jery
    age: 19
    addr: nanchang

student1: [{name: tom,age: 19,addr: beijing}]

#map配置
map:
  key1: value1
  key2: value2




